
# config/routes.yaml
authentication_token:
    path: /api/login
    methods: ['POST']

showFormateur:
    path: /api/formateurs
    controller: App\Controller\UserController::showFormateur
    methods: ['GET']

    
showFormateurById:
    path: /api/formateurs/{id}
    controller: App\Controller\UserController::showFormateurById
    methods: ['GET']

showApprenant:
    path: /api/apprenants
    controller: App\Controller\UserController::showApprenant
    methods: ['GET']
    
showApprenantById:
    path: /api/apprenants/{id}
    controller: App\Controller\UserController::showApprenantById
    methods: ['GET']
    
 