
# config/routes.yaml
authentication_token:
    path: /api/login
    methods: ['POST']

showFormateur:
    path: /api/formateurs
    controller: App\Controller\UserController::showFormateur
    methods: ['GET']

    
showFormateurById:
    path: /api/formateurs/{id}
    controller: App\Controller\UserController::showFormateurById
    methods: ['GET','PUT']

showApprenant:
    path: /api/apprenants
    controller: App\Controller\UserController::showApprenant
    methods: ['GET']

addApprenant:
    path: /api/apprenants
    controller: App\Controller\UserController::addApprenant
    methods: ['POST']
    
showApprenantById:
    path: /api/apprenants/{id}
    controller: App\Controller\UserController::showApprenantById
<<<<<<< HEAD
    methods: ['GET','PUT']   

# config/routes.yaml
authentication_token:
    path: /api/login
    methods: ['POST']
=======
    methods: ['GET']
    
 
>>>>>>> adf7a40c1139c3cfef3a68a3279f10afe6860594
